### ISSUE TITLE
Syntax Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Jacky9425** [parryworld/react-native-appupdate#18]
Hi, i am using dropbox to host both version.json and the new version apk file. On running the app, the app loads well but console shows `getVersionError Syntax Error: Unexpected token < in JSON at position 0`. May i know what does this error means and how to solve it? Does the app failed to get the current version or the version mentioned in version.json?

**Comment by mikehardy** [comment]
I tried dropbox and saw this as well. You need to put '?raw=1' on your link or dropbox shared links don't work.

I have a fork going here https://github.com/mikehardy/react-native-update-apk that is based on this code but has been updated and fixed such that it seems to work for API16-API28, even for SSL links, with a working example.

Good luck
